---
- name: Install and Start Nginx
  hosts: web
  become: true

  tasks:

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: true
