name: Context Demo

on:
  push:
  workflow_dispatch:

jobs:
  context-demo:

    runs-on: ubuntu-latest

    steps:

      - name: Display Runner 
        run: |
          echo "OS = ${{ runner.os }}"
          echo "Architecture = ${{ runner.arch }}"
          echo "Runner Name = ${{ runner.name }}"
