name: Secret Demo

on:
  workflow_dispatch:

jobs:
  secret-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Read Secret
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          echo "Secret length is: ${#DEMO_SECRET}"
          echo "Secret value is: $DEMO_SECRET"
