name: AWS Terraform Ansible

on:
  workflow_dispatch:

jobs:

  # ==========================================
  # JOB 1 - TEST AWS CONNECTION
  # ==========================================

  aws-test:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Check AWS Identity
        run: |
          aws sts get-caller-identity


  # ==========================================
  # JOB 2 - TERRAFORM
  # ==========================================

  terraform:

    needs: aws-test

    runs-on: ubuntu-latest

    outputs:
      ec2_ip: ${{ steps.get_ip.outputs.ec2_ip }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Check Terraform Version
        run: |
          terraform version


      - name: Terraform Init
        run: |
          terraform init


      - name: Terraform Validate
        run: |
          terraform validate


      - name: Terraform Plan
        run: |
          terraform plan


      - name: Terraform Apply
        run: |
          terraform apply -auto-approve


      - name: Get EC2 IP
        id: get_ip
        run: |
          echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> "$GITHUB_OUTPUT"


  # ==========================================
  # JOB 3 - ANSIBLE
  # ==========================================

  ansible:

    needs: terraform

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------
      # CHECKOUT
      # ------------------------------------------

      - name: Checkout Code
        uses: actions/checkout@v4


      # ------------------------------------------
      # INSTALL ANSIBLE
      # ------------------------------------------

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible


      - name: Check Ansible Version
        run: |
          ansible --version


      # ------------------------------------------
      # CREATE SSH KEY
      # ------------------------------------------

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem


      # ------------------------------------------
      # CHECK EC2 PYTHON
      # ------------------------------------------

      - name: Check EC2 Python
        run: |
          ssh -i ec2-key.pem \
            -o StrictHostKeyChecking=no \
            ec2-user@${{ needs.terraform.outputs.ec2_ip }} \
            "cat /etc/os-release && echo '--- Python ---' && python3 --version && echo '--- Path ---' && which python3"


      # ------------------------------------------
      # CREATE INVENTORY
      # ------------------------------------------

      - name: Create Ansible Inventory
        run: |
          echo "[web]" > inventory

          echo "${{ needs.terraform.outputs.ec2_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=./ec2-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory


      # ------------------------------------------
      # SHOW INVENTORY
      # ------------------------------------------

      - name: Show Inventory
        run: |
          cat inventory


      # ------------------------------------------
      # TEST ANSIBLE
      # ------------------------------------------

      - name: Test Ansible Connection
        run: |
          ansible web -i inventory -m ping


      # ------------------------------------------
      # RUN PLAYBOOK
      # ------------------------------------------

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory playbook.yml
