name: Terraform Artifact Demo

on: [push]

jobs:
  terraform-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Terraform Output
        run: terraform output -raw instance_ip > ec2_ip.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ec2-ip
          path: ec2_ip.txt
